Data:
  train_dir: /data/train
  test_dir: /data/test
  artifact_dir: /wdata
Dataloader:
  train_batch_size: 10
  train_num_workers: 6
  val_batch_size: 8
  val_num_workers: 6
  test_batch_size: 8
  test_num_workers: 6
Transform:
  train_random_crop_size: [352, 352]
  train_random_flip_prob: 0.0  # both of left-right and top-bottom
Model:
  type: siamese
  arch: unet
  encoder: timm-efficientnet-b3
  n_input_post_images: 1
  n_siamese_head_convs: 2
Class:
  groups: [building, road]
  classes:
    building: [flood_building, not_flood_building]
    road: [flood_road, not_flood_road]
  class_weights:
    building: [1.0, 1.0]
    road: [1.0, 1.0]
  losses:
    building: [dice, bce, ce]
    road:  [dice, bce, ce]
  loss_weights:
    building: [1.0, 1.0, 1.0]
    road: [1.0, 1.0, 1.0]
Optimizer:
  type: adam
  lr: 1e-4  # 2e-4 might be better if train from scratch
  weight_decay: 0
Scheduler:
  type: multistep
  multistep_milestones: [80, 120]
  multistep_gamma: 0.1
  annealing_t_max: 140
  annealing_eta_min: 0.0
General:
  gpus: [0]
  epochs: 140
  fp16: true
  amp_backend: native # valid when fp16=true
  amp_level: null # valid when amp_backend=apex
  seed: 777
  deterministic: true
  benchmark: false
  check_val_every_n_epoch: 1