Data:
  train_dir: /data/train
  test_dir: /data/test
  artifact_dir: /wdata
Dataloader:
  train_batch_size: 10
  train_num_workers: 6
  val_batch_size: 8
  val_num_workers: 6
  test_batch_size: 8
  test_num_workers: 6
Transform:
  train_random_crop_size: [512, 512]
Model:
  arch: unet
  encoder: timm-efficientnet-b3
  classes: [building, building_border, building_contact]
Loss:
  types: ['dice', 'bce']
  weights: [1.0, 1.0]
  class_weights: [1.0, 1.0, 1.0]
Optimizer:
  type: adam
  lr: 2e-4
  weight_decay: 0
Scheduler:
  type: multistep
  multistep_milestones: [80, 120]
  multistep_gamma: 0.1
General:
  gpus: [0]
  epochs: 140
  fp16: true
  amp_backend: native # valid when fp16=true
  amp_level: null # valid when amp_backend=apex
  seed: 777
  deterministic: true
  benchmark: false
