Data:
  train_dir: /data/train
  test_dir: /data/test
  artifact_dir: /wdata
  fold_ver: folds_v1
Dataloader:
  train_batch_size: 10
  train_num_workers: 6
  val_batch_size: 8
  val_num_workers: 6
  test_batch_size: 8
  test_num_workers: 6
Transform:
  train_random_crop_size: [512, 512]
  train_random_flip_prob: 0.0  # both of horizontal and vertical flip
  train_random_horizontal_flip_prob: 0.0
  train_random_vertical_flip_prob: 0.0
  train_random_rotate90_prob: 0.0
Model:
  type: seg
  arch: unet
  encoder: timm-efficientnet-b3
  n_input_post_images: 0
  n_siamese_head_convs: 2
Class:
  groups: [road]
  classes:
    road: [road, road_junction]
  class_weights:
    road: [1.0, 1.0]
  losses:
    road: [dice, bce]
  loss_weights:
    road: [1.0, 1.0]
Optimizer:
  type: adam
  lr: 2e-4
  weight_decay: 0
Scheduler:
  type: multistep
  multistep_milestones: [80, 120]
  multistep_gamma: 0.1
  annealing_t_max: 140
  annealing_eta_min: 0.0
General:
  gpus: [0]
  epochs: 140
  fp16: true
  amp_backend: native # valid when fp16=true
  amp_level: null # valid when amp_backend=apex
  seed: 777
  deterministic: true
  benchmark: false
  check_val_every_n_epoch: 1