Data:
  train_dir: /data/train
  test_dir: /data/test
  artifact_dir: /wdata
  fold_id: 0
Dataloader:
  train_batch_size: 16
  train_num_workers: 6
  val_batch_size: 8
  val_num_workers: 6
Transform:
  train_random_crop_size: [320, 320]
  test_size: [1312, 1312]
Model:
  arch: unet
  encoder: timm-efficientnet-b3
  classes: [building, building_border, building_contact]
General:
  gpus: [0]
  epochs: 50
  fp16: true
  amp_backend: native # valid when fp16=true
  amp_level: null # valid when amp_backend=apex
  seed: 777
  deterministic: true
  benchmark: false
exp_id: 9999
