Dataloader:
  train_batch_size: 16
  val_batch_size: 16
  train_num_workers: 8
  val_num_workers: 8
Transform:
  train_random_crop_size: [448, 448]
Model:
  encoder: timm-efficientnet-b5
Optimizer:
  lr: 4e-4